// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.0
// source: protos/vote.proto

package voteDao

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vote_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vote_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protos_vote_proto_rawDescGZIP(), []int{0}
}

type InsertResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectID []byte `protobuf:"bytes,1,opt,name=objectID,proto3" json:"objectID,omitempty"`
}

func (x *InsertResult) Reset() {
	*x = InsertResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vote_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResult) ProtoMessage() {}

func (x *InsertResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vote_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResult.ProtoReflect.Descriptor instead.
func (*InsertResult) Descriptor() ([]byte, []int) {
	return file_protos_vote_proto_rawDescGZIP(), []int{1}
}

func (x *InsertResult) GetObjectID() []byte {
	if x != nil {
		return x.ObjectID
	}
	return nil
}

type Rating struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Rating int32  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *Rating) Reset() {
	*x = Rating{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vote_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rating) ProtoMessage() {}

func (x *Rating) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vote_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rating.ProtoReflect.Descriptor instead.
func (*Rating) Descriptor() ([]byte, []int) {
	return file_protos_vote_proto_rawDescGZIP(), []int{2}
}

func (x *Rating) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Rating) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type Target struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val string `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *Target) Reset() {
	*x = Target{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vote_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vote_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_protos_vote_proto_rawDescGZIP(), []int{3}
}

func (x *Target) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type Vote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender  string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Target  string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Vote    int32  `protobuf:"varint,3,opt,name=vote,proto3" json:"vote,omitempty"`
	VotedAt int64  `protobuf:"varint,4,opt,name=votedAt,json=voted_at,omitempty,proto3" json:"votedAt,omitempty"`
}

func (x *Vote) Reset() {
	*x = Vote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vote_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vote_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_protos_vote_proto_rawDescGZIP(), []int{4}
}

func (x *Vote) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Vote) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Vote) GetVote() int32 {
	if x != nil {
		return x.Vote
	}
	return 0
}

func (x *Vote) GetVotedAt() int64 {
	if x != nil {
		return x.VotedAt
	}
	return 0
}

type VoteFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vote     *Vote `protobuf:"bytes,1,opt,name=vote,proto3" json:"vote,omitempty"`
	IsTarget bool  `protobuf:"varint,2,opt,name=isTarget,proto3" json:"isTarget,omitempty"`
	IsSender bool  `protobuf:"varint,3,opt,name=isSender,proto3" json:"isSender,omitempty"`
}

func (x *VoteFilter) Reset() {
	*x = VoteFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vote_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteFilter) ProtoMessage() {}

func (x *VoteFilter) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vote_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteFilter.ProtoReflect.Descriptor instead.
func (*VoteFilter) Descriptor() ([]byte, []int) {
	return file_protos_vote_proto_rawDescGZIP(), []int{5}
}

func (x *VoteFilter) GetVote() *Vote {
	if x != nil {
		return x.Vote
	}
	return nil
}

func (x *VoteFilter) GetIsTarget() bool {
	if x != nil {
		return x.IsTarget
	}
	return false
}

func (x *VoteFilter) GetIsSender() bool {
	if x != nil {
		return x.IsSender
	}
	return false
}

var File_protos_vote_proto protoreflect.FileDescriptor

var file_protos_vote_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x76, 0x6f, 0x74, 0x65, 0x44, 0x61, 0x6f, 0x22, 0x07, 0x0a, 0x05,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x2a, 0x0a, 0x0c, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49,
	0x44, 0x22, 0x38, 0x0a, 0x06, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x1a, 0x0a, 0x06, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x6f, 0x0a, 0x04, 0x56, 0x6f, 0x74, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x76,
	0x6f, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x07, 0x76, 0x6f, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x76, 0x6f, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x2c, 0x6f,
	0x6d, 0x69, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x67, 0x0a, 0x0a, 0x56, 0x6f, 0x74, 0x65,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x76, 0x6f, 0x74, 0x65, 0x44, 0x61, 0x6f, 0x2e, 0x56,
	0x6f, 0x74, 0x65, 0x52, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x53, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x53, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x32, 0xf5, 0x01, 0x0a, 0x08, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x12, 0x39,
	0x0a, 0x11, 0x46, 0x69, 0x6e, 0x64, 0x56, 0x6f, 0x74, 0x65, 0x49, 0x6e, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x12, 0x13, 0x2e, 0x76, 0x6f, 0x74, 0x65, 0x44, 0x61, 0x6f, 0x2e, 0x56, 0x6f,
	0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x1a, 0x0d, 0x2e, 0x76, 0x6f, 0x74, 0x65, 0x44,
	0x61, 0x6f, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x13, 0x49, 0x6e, 0x73,
	0x65, 0x72, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x54, 0x6f, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x12, 0x0d, 0x2e, 0x76, 0x6f, 0x74, 0x65, 0x44, 0x61, 0x6f, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x1a,
	0x15, 0x2e, 0x76, 0x6f, 0x74, 0x65, 0x44, 0x61, 0x6f, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x56, 0x6f, 0x74, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x12, 0x13, 0x2e, 0x76, 0x6f, 0x74, 0x65, 0x44, 0x61, 0x6f, 0x2e, 0x56, 0x6f, 0x74, 0x65,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x1a, 0x0e, 0x2e, 0x76, 0x6f, 0x74, 0x65, 0x44, 0x61, 0x6f,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x52,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x0f, 0x2e, 0x76, 0x6f, 0x74, 0x65, 0x44, 0x61, 0x6f, 0x2e,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x1a, 0x0f, 0x2e, 0x76, 0x6f, 0x74, 0x65, 0x44, 0x61, 0x6f,
	0x2e, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x76, 0x6f,
	0x74, 0x65, 0x44, 0x61, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_vote_proto_rawDescOnce sync.Once
	file_protos_vote_proto_rawDescData = file_protos_vote_proto_rawDesc
)

func file_protos_vote_proto_rawDescGZIP() []byte {
	file_protos_vote_proto_rawDescOnce.Do(func() {
		file_protos_vote_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_vote_proto_rawDescData)
	})
	return file_protos_vote_proto_rawDescData
}

var file_protos_vote_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protos_vote_proto_goTypes = []interface{}{
	(*Empty)(nil),        // 0: voteDao.Empty
	(*InsertResult)(nil), // 1: voteDao.InsertResult
	(*Rating)(nil),       // 2: voteDao.Rating
	(*Target)(nil),       // 3: voteDao.Target
	(*Vote)(nil),         // 4: voteDao.Vote
	(*VoteFilter)(nil),   // 5: voteDao.VoteFilter
}
var file_protos_vote_proto_depIdxs = []int32{
	4, // 0: voteDao.VoteFilter.vote:type_name -> voteDao.Vote
	5, // 1: voteDao.VoteRepo.FindVoteInStorage:input_type -> voteDao.VoteFilter
	4, // 2: voteDao.VoteRepo.InsertVoteToStorage:input_type -> voteDao.Vote
	5, // 3: voteDao.VoteRepo.DeleteVoteFromStorage:input_type -> voteDao.VoteFilter
	3, // 4: voteDao.VoteRepo.GetRating:input_type -> voteDao.Target
	4, // 5: voteDao.VoteRepo.FindVoteInStorage:output_type -> voteDao.Vote
	1, // 6: voteDao.VoteRepo.InsertVoteToStorage:output_type -> voteDao.InsertResult
	0, // 7: voteDao.VoteRepo.DeleteVoteFromStorage:output_type -> voteDao.Empty
	2, // 8: voteDao.VoteRepo.GetRating:output_type -> voteDao.Rating
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_vote_proto_init() }
func file_protos_vote_proto_init() {
	if File_protos_vote_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_vote_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vote_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vote_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rating); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vote_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Target); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vote_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vote_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_vote_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_vote_proto_goTypes,
		DependencyIndexes: file_protos_vote_proto_depIdxs,
		MessageInfos:      file_protos_vote_proto_msgTypes,
	}.Build()
	File_protos_vote_proto = out.File
	file_protos_vote_proto_rawDesc = nil
	file_protos_vote_proto_goTypes = nil
	file_protos_vote_proto_depIdxs = nil
}
