// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.0
// source: protos/vote.proto

package vote

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vote_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vote_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protos_vote_proto_rawDescGZIP(), []int{0}
}

type VoteArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender  string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Target  string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Vote    int32  `protobuf:"varint,3,opt,name=vote,proto3" json:"vote,omitempty"`
	VotedAt int64  `protobuf:"varint,4,opt,name=votedAt,json=voted_at,omitempty,proto3" json:"votedAt,omitempty"`
}

func (x *VoteArg) Reset() {
	*x = VoteArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vote_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteArg) ProtoMessage() {}

func (x *VoteArg) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vote_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteArg.ProtoReflect.Descriptor instead.
func (*VoteArg) Descriptor() ([]byte, []int) {
	return file_protos_vote_proto_rawDescGZIP(), []int{1}
}

func (x *VoteArg) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *VoteArg) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *VoteArg) GetVote() int32 {
	if x != nil {
		return x.Vote
	}
	return 0
}

func (x *VoteArg) GetVotedAt() int64 {
	if x != nil {
		return x.VotedAt
	}
	return 0
}

type RetractArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Sender string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (x *RetractArg) Reset() {
	*x = RetractArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vote_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetractArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetractArg) ProtoMessage() {}

func (x *RetractArg) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vote_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetractArg.ProtoReflect.Descriptor instead.
func (*RetractArg) Descriptor() ([]byte, []int) {
	return file_protos_vote_proto_rawDescGZIP(), []int{2}
}

func (x *RetractArg) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RetractArg) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type Target struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *Target) Reset() {
	*x = Target{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vote_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vote_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_protos_vote_proto_rawDescGZIP(), []int{3}
}

func (x *Target) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type Rating struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Rating int32  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *Rating) Reset() {
	*x = Rating{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vote_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rating) ProtoMessage() {}

func (x *Rating) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vote_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rating.ProtoReflect.Descriptor instead.
func (*Rating) Descriptor() ([]byte, []int) {
	return file_protos_vote_proto_rawDescGZIP(), []int{4}
}

func (x *Rating) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Rating) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

var File_protos_vote_proto protoreflect.FileDescriptor

var file_protos_vote_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x72, 0x0a, 0x07, 0x56, 0x6f, 0x74, 0x65, 0x41, 0x72, 0x67, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x76, 0x6f, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x76, 0x6f, 0x74,
	0x65, 0x12, 0x23, 0x0a, 0x07, 0x76, 0x6f, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x12, 0x76, 0x6f, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x2c, 0x6f, 0x6d, 0x69,
	0x74, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x3c, 0x0a, 0x0a, 0x52, 0x65, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x41, 0x72, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x22, 0x20, 0x0a, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x38, 0x0a, 0x06, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x32, 0x91, 0x01, 0x0a, 0x0e, 0x56, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x04, 0x56, 0x6f, 0x74, 0x65, 0x12, 0x0d, 0x2e, 0x76, 0x6f,
	0x74, 0x65, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x41, 0x72, 0x67, 0x1a, 0x0b, 0x2e, 0x76, 0x6f, 0x74,
	0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x0b, 0x52, 0x65, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x12, 0x10, 0x2e, 0x76, 0x6f, 0x74, 0x65, 0x2e,
	0x52, 0x65, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x72, 0x67, 0x1a, 0x0b, 0x2e, 0x76, 0x6f, 0x74,
	0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x09, 0x47, 0x65, 0x74,
	0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x0c, 0x2e, 0x76, 0x6f, 0x74, 0x65, 0x2e, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x1a, 0x0c, 0x2e, 0x76, 0x6f, 0x74, 0x65, 0x2e, 0x52, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2f, 0x76, 0x6f, 0x74, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_vote_proto_rawDescOnce sync.Once
	file_protos_vote_proto_rawDescData = file_protos_vote_proto_rawDesc
)

func file_protos_vote_proto_rawDescGZIP() []byte {
	file_protos_vote_proto_rawDescOnce.Do(func() {
		file_protos_vote_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_vote_proto_rawDescData)
	})
	return file_protos_vote_proto_rawDescData
}

var file_protos_vote_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_vote_proto_goTypes = []interface{}{
	(*Empty)(nil),      // 0: vote.Empty
	(*VoteArg)(nil),    // 1: vote.VoteArg
	(*RetractArg)(nil), // 2: vote.RetractArg
	(*Target)(nil),     // 3: vote.Target
	(*Rating)(nil),     // 4: vote.Rating
}
var file_protos_vote_proto_depIdxs = []int32{
	1, // 0: vote.VoteController.Vote:input_type -> vote.VoteArg
	2, // 1: vote.VoteController.RetractVote:input_type -> vote.RetractArg
	3, // 2: vote.VoteController.GetRating:input_type -> vote.Target
	0, // 3: vote.VoteController.Vote:output_type -> vote.Empty
	0, // 4: vote.VoteController.RetractVote:output_type -> vote.Empty
	4, // 5: vote.VoteController.GetRating:output_type -> vote.Rating
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_vote_proto_init() }
func file_protos_vote_proto_init() {
	if File_protos_vote_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_vote_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vote_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vote_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetractArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vote_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Target); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vote_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rating); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_vote_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_vote_proto_goTypes,
		DependencyIndexes: file_protos_vote_proto_depIdxs,
		MessageInfos:      file_protos_vote_proto_msgTypes,
	}.Build()
	File_protos_vote_proto = out.File
	file_protos_vote_proto_rawDesc = nil
	file_protos_vote_proto_goTypes = nil
	file_protos_vote_proto_depIdxs = nil
}
